export enum IPCChannels {
  GetRootVideoData = "get:root-video-data",
  GetVideoJsonData = "get:video-json-data",
  SaveVideoJsonData = "save:video-json-data",
  SaveLastWatch = "save:lastWatch",
  DeleteVideo = "delete:video",
  OpenFileDialog = "open-file-dialog",
  GetAllPlaylists = "playlist:getAllPlaylists",
  DeletePlaylist = "playlist:deletePlaylist",
  DeletePlaylistVideo = "playlist:deletePlaylistVideo",
  UpdatePlaylistName = "playlist:updatePlaylistName",
  AddNewPlaylist = "playlist:addNewPlaylist",
  addOrRemoveVideoFromPlaylist = "playlist:addOrRemoveVideoFromPlaylist",
  GetVideoData = "playlist:getVideoData",
  YoutubeVideoDownload = "youtube:videoDownload",
  YoutubeVideoDetails = "youtube:videoDetails",
}
